DatabaseMirror database.clamav.net
DNSDatabaseInfo current.cvd.clamav.net
DatabaseOwner onebrain
Checks 4
ConnectTimeout 30
ReceiveTimeout 120
TestDatabases yes
CompressLocalDatabase no
Bytecode yes
ScriptedUpdates yes
